apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "kumarawnish840@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "aqgv rygj zevl kptu"
type: Opaque

# Passw0rd@1234
